### ISSUE TITLE
change CRA "PUBLIC_URL" post build process

### ISSUE THREAD

**Issue by kkarkos** [staticdeploy/app-server#6]
Hi, 

your comment on https://github.com/facebook/create-react-app/issues/2353 brought me here. I'm facing the problem that a client wants to serve ONE CRA build on different static server without using pipelines etc.. So the "PUBLIC_URL" would need to change post build based on a config file so the files can be server from the correct "static" folder. 

You are writing 
> When serving the files, I also implemented some best-match redirects to allow the app base url (PUBLIC_URL) to be configured at runtime as well.

Could you please point me in the right direction? I can't find anything about "best-match redirects" in the docs.

Cheers

**Comment by pscanf** [comment]
Hey @kkarkos , sorry for the late reply, I saw the issue while on vacation and then forgot about it.

The comment you quoted was a bit inaccurate on my part, and so maybe a bit misleading. `app-server` does not dynamically change your app's `PUBLIC_URL`, rather, it serves _the correct content_ even when you set `PUBLIC_URL` (at build time) to `.`, making all links relative. The outcome though is basically the same: at runtime you can change the base url of the app without having to rebuild it (though you might have to change `app-server`'s config option `--basePath`, but that's a runtime configuration). [Here you can find a bit of documentation explaining how requests are routed](https://github.com/staticdeploy/app-server/blob/master/docs/requests-routing.md) so that _the correct content is served_.

I actually forgot to add this info to [the doc on how to use `app-server` with CRA](https://github.com/staticdeploy/app-server/blob/master/docs/usage-with-cra.md), I will put it in now.

Thanks for reporting, let me know if you still have issues
